#service.yaml:
#---
#de
apiVersion: v1
kind: Service
metadata:
  name: kube-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: frontend
    
    #deployment.yaml:
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstkube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: hello-world-app-container
        image: gcr.io/speedy-aurora-351809/version:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
