---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: frontend
  ports:
    - targetPort: 8080
      port: 80
  type: LoadBalancer

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: frontend
    color: green
  name: green-deploy
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: frontend
      color: green
  template: 
    metadata: 
      labels: 
        app: frontend
        color: green
      name: green-deploy
    spec: 
      containers: 
        - image: gcr.io/speedy-aurora-351809/version:c080d1ac0ee1326cf76c31feee271e6c97ec3dd3
          imagePullPolicy: IfNotPresent
          name: green-deploy
          ports: 
            - containerPort: 8080
