#deploymnet
---
apiVersion: v1
kind: Service
metadata:
  name: kube-service
spec:
  selector:
    app: backened
  ports:
    - targetPort: 8080
      port: 80
  type: LoadBalancer

--- 





apiVersion: apps/v1

kind: Deployment

metadata:

  name: kube-deployment

  labels:

    app: backened

spec:

  replicas: 3

  selector:

    matchLabels:

      app: backened

  template:

    metadata:

      labels:

        app: backened

    spec:

      containers:

      - name: kube-container

        image: gcr.io/speedy-aurora-351809/version:latest
        imagePullPolicy: Always
        ports:

        - containerPort: 80

